[versions]
dokka = "1.9.20"
kotlin = "2.0.0"
junit = "4.13.2"
kotlinPoet = "1.16.0"
ksp = "2.0.0-1.0.21"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinPoet = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }
ksp-symbolProcessingApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
